# Generated by Django 5.0.6 on 2024-06-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SolarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleaning_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repair_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solar_need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.solarneed')),
            ],
        ),
    ]
